ci: enhance build-and-push workflow with versioning and deployment triggers

diff --git a/.github/workflows/build-and-push.yml b/.github/workflows/build-and-push.yml
--- a/.github/workflows/build-and-push.yml
+++ b/.github/workflows/build-and-push.yml
@@ -1,11 +1,13 @@
 name: build-and-push
 on:
+  issue_comment:
+    types: [created]
   push:
     branches:
-        - "**"
-  
+      - main
+
 env:
-  AWS_REGION: us-east-1                 
+  AWS_REGION: us-east-1
   ECR_REPOSITORY: app/web
   EKS_CLUSTER_NAME: EKS-lanchonete-cluster
 
@@ -23,6 +25,24 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Check for deploy-dev comment
+        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/deploy-dev')
+        run: echo "Deploying to development environment..."
+
+      - name: Versioning image
+        id: image-tag
+        run: |
+          if [[ "${{ github.event_name }}" == 'push' && "${{ github.ref }}" == "refs/head/main" ]]; then
+           # Versioning the production image, incrementing the semantic version!
+            VERSION=$(cat VERSION)
+            NEW_VERSION=$(echo $VERSION | awk -F. '{print $1"."$2"."$3+1}')
+            echo $NEW_VERSION > VERSION
+            echo "tag=$NEW_VERSION" >> $GITHUB_ENV
+          else
+            # Versioning the development image, using the commit SHA!
+            echo "tag=${{ github.sha }}-dev" >> $GITHUB_ENV
+          fi
+
       - name: Configure AWS credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
@@ -38,45 +58,55 @@ jobs:
           registry-type: private
           mask-password: true
 
-      - name: Build the container image
+      - name: Build and push the container image
         id: build
         env:
           ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
-          IMAGE_TAG: ${{ github.sha }}
           GITHUB_OUTPUT: $GITHUB_ENV
+        #   IMAGE_TAG: ${{ github.sha }}
         run: |
-          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
-          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
+          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.tag }} .
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.tag }}
+
+      - name: Commit and push updated version
+        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "github-actions[bot]@users.noreply.github.com"
+          git add VERSION
+          git commit -m "ci: bump version to ${{ env.tag }}"
+          git push origin main
 
       - name: Setup Kubeconfig
         run: aws eks --region $AWS_REGION update-kubeconfig --name $EKS_CLUSTER_NAME
 
-      - name: Deploy app in Kubernetes
+      - name: Deploy app in Kubernetes cluster
+        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/deploy-dev')
         env:
           IMAGE: ${{ steps.build.outputs.image }}
+          GITHUB_OUTPUT: $GITHUB_ENV
         run: |
-          echo "image=$IMAGE" >> $GITHUB_ENV
-          echo "ENVIRONMENT=development" >> $GITHUB_ENV
-          echo "KUSTOMIZE_DIR=$(pwd)/infra/kubernetes/development" >> $GITHUB_ENV
-
-          echo "Image tag: $IMAGE"
-          
           source $GITHUB_ENV
+
+          ENVIRONMENT=development
+          KUSTOMIZE_DIR=$(pwd)/infra/kubernetes/development
+
+          if [[ "${{ github.event_name }}" == 'push' && "${{ github.ref }}" == "refs/heads/main" ]]; then
+          ENVIRONMENT=production
+          KUSTOMIZE_DIR=$(pwd)/infra/kubernetes/production
+          fi
+
+          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
+          echo "KUSTOMIZE_DIR=$KUSTOMIZE_DIR" >> $GITHUB_ENV
 
           cd $KUSTOMIZE_DIR
           pwd && ls -la
 
+          # Check if namespace exists, if not create it
           kubectl get namespace $ENVIRONMENT || kubectl create namespace $ENVIRONMENT
 
-          kustomize edit set image web=$IMAGE
-          
-          echo "Deploying resources in $ENVIRONMENT environment..."
-          kubectl apply -k $KUSTOMIZE_DIR -n $ENVIRONMENT
+          kustomize edit set image web=${{ env.tag }}
 
-          if [ $? -eq 0 ]; then
-            echo "Resources deployed successfully!"
-          else
-            echo "Failed to deploy resources!"
-            exit 1
-          fi
+          echo "Deploying resources in $ENVIRONMENT environment"
+          echo "Using image version: ${{ env.tag }}"
+          kubectl apply -k $KUSTOMIZE_DIR -n $ENVIRONMENT && echo "Resources deployed successfully!" || (echo "Failed to deploy resources!" && exit 1)
