fix: update image version variable usage in deployment workflow

diff --git a/.github/workflows/deploy-dev.yml b/.github/workflows/deploy-dev.yml
--- a/.github/workflows/deploy-dev.yml
+++ b/.github/workflows/deploy-dev.yml
@@ -63,9 +63,9 @@ jobs:
             # Check if namespace exists, if not create it
             kubectl get namespace $ENVIRONMENT || kubectl create namespace $ENVIRONMENT
             
-            kustomize edit set image web=$ECR_REGISTRY/$ECR_REPOSITORY:${{ env.image-version }}
+            kustomize edit set image web=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_VERSION
 
             echo "Deploying resource in $ENVIRONMENT namespace."
 
-            echo "Using image version: ${{ env.image-version }}"
-            kubectl apply -k $KUSTOMIZE_DIR -n $ENVIRONMENT && echo "Resources deployed successfully!" || {echo "Failed to deploy resources! Check the logs"; kubectl describe pods -n $ENVIRONMENT; exit 1; }
+            echo "Using image version: $IMAGE_VERSION"
+            kubectl apply -k $KUSTOMIZE_DIR -n $ENVIRONMENT && echo "Resources deployed successfully!" || { echo "Failed to deploy resources! Check the logs"; kubectl describe pods -n $ENVIRONMENT; exit 1; }
